apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq
  namespace: default
spec:
  hard:
    pods: "10"
    services: "5"
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
